Freshao
DevOps-Spring-2022-Recommendations/recommendations pull request #68
Opened 2022-03-05 23:22 UTC by freshao1017

Need ability to Delete a recommendation

2022-03-05 23:23 UTC, aianurag09 commented
Changing merge branch from changtk to main
so that we can clearly observe the changed @freshao1017

2022-03-05 23:27 UTC, freshao1017 commented
> 

I have changed it.

2022-03-05 23:30 UTC, freshao1017 commented
> > 
> 
> I have changed it.

2022-03-05 23:36 UTC, aianurag09 commented
You need to have the base branch as changtk, so that we can easily track what updates are made. Hence I changed to changtk, let the base branch be changtk. I'm updating it now @freshao1017

2022-03-05 23:37 UTC, changtk07 requested changes
Reviews

2022-03-05 23:37 UTC, changtk07 commented on service/routes.py
> +def delete_recommendation(item_id):
Should use plural here, `delete_recommendations`

2022-03-05 23:37 UTC, changtk07 commented on tests/test_models.py
> +        product.delete()
should be `recommendation`

2022-03-05 23:39 UTC, aianurag09 commented
Please make sure you run nosetests to see how the code coverage is

2022-03-06 01:17 UTC, freshao1017 commented
@aianurag09 Do you want me to merge into main or changtk? You changed my base to changtk

2022-03-06 01:24 UTC, changtk07 approved these changes
Approved

2022-03-06 01:25 UTC, aianurag09 approved these changes

2022-03-06 22:50 UTC, changtk07 requested changes

2022-03-06 22:50 UTC, changtk07 commented on tests/test_routes.py
> +        test_recommendation = self._create_recommendation(1)[0]
`_create_recommendation` -> `_create_recommendations`

2022-03-07 03:02 UTC, changtk07 approved these changes

2022-03-07 03:07 UTC, merged