Calboy404 patch 1
DevOps-Spring-2022-Recommendations/recommendations pull request #69
Opened 2022-03-06 16:08 UTC by calboy404

2022-03-06 16:09 UTC, calboy404 commented
Added the ability to update recommendations

2022-03-06 17:24 UTC, aianurag09 commented on service/models.py
> +        if type(self.price) is not int:
There is no price in the Recomendation Model, change the code according to the attributes of Recommendation model i.e src_prod_id etc.

2022-03-06 17:25 UTC, aianurag09 commented on tests/test_models.py
> +        recommendation = Recommendation(id=1, name="iPhone", category="phone", price=100)
The attributes are change refer to attributes in model.spy

2022-03-06 17:27 UTC, aianurag09 commented
@calboy404 you didn;t change the code according to the attributes, refer to other pull requests and models.py and change accordingly

2022-03-06 19:27 UTC, aianurag09 approved these changes

2022-03-06 19:27 UTC, aianurag09 commented on tests/test_models.py
> +        recommendation = Recommendation(id=1, name="iPhone", category="Phone", price="100")
same change the attributes and check with the attributes in modes.phy

2022-03-06 19:28 UTC, aianurag09 commented
Done @calboy404

2022-03-06 19:46 UTC, changtk07 requested changes
Please run nosetests, these error won't even pass the tests

2022-03-06 19:46 UTC, changtk07 commented on service/models.py
> +        logger.info("Saving %s", self.name)
There's no `name` attribute, use `id`

2022-03-06 19:46 UTC, changtk07 commented on service/models.py
> +        if type(self.id) is not int:
Line 61-66, no need to check these

2022-03-06 19:46 UTC, changtk07 commented on service/routes.py
> +    app.logger.info("recommendation with ID [%s] updated.", product.id)
`product` -> `recommendation`

2022-03-06 19:46 UTC, changtk07 commented on tests/test_models.py
> +        """Update an item"""
item -> recommendation

2022-03-06 19:46 UTC, changtk07 commented on tests/test_models.py
> +        recommendation = Recommendation(id=1, src_product_id=100, rec_product_id = 200, type= "UP_SELL")
What's the difference of this test and line 138?

2022-03-06 19:46 UTC, changtk07 commented on tests/test_routes.py
> +        new_recommendation["category"] = "unknown"
no `category` attribute

2022-03-06 19:46 UTC, changtk07 commented on tests/test_routes.py
> +        self.assertEqual(updated_recommendation["category"], "unknown")
no `category` attribute

2022-03-06 22:02 UTC, changtk07 requested changes

2022-03-06 22:02 UTC, changtk07 commented on service/models.py
> +     def update(self):
Wrong indentation

2022-03-06 22:02 UTC, changtk07 commented on tests/test_routes.py
> +     def test_update_recommendatio(self):
Wrong indentation

2022-03-07 03:11 UTC, changtk07 approved these changes

2022-03-07 03:11 UTC, merged