List Recommendations by Source ID
DevOps-Spring-2022-Recommendations/recommendations pull request #83
Opened 2022-04-04 02:38 UTC by aianurag09

2022-04-04 16:25 UTC, freshao1017 commented on service/routes.py
> +        recommendations = Recommendation.all()
How should we combined src_product_id and rec_product_id together in the same function?

2022-04-06 20:34 UTC, changtk07 requested changes

2022-04-06 20:34 UTC, changtk07 commented on tests/test_routes.py
> +    def test_query_pet_recommendations_by_source(self):
what is a pet recommendation?

2022-04-06 20:34 UTC, changtk07 commented on tests/test_models.py
> +    def test_find_by_sourceID(self):
naming convention...

2022-04-06 20:34 UTC, changtk07 commented on service/models.py
> +=======
run the code before PR.....

2022-04-06 21:49 UTC, closed without merging